version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    container_name: db_app
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env-non-dev 
    volumes:
      - ./db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: fastapi_app
    restart: unless-stopped
    env_file:
      - .env-non-dev
    ports:
      - "8080:8080"
    depends_on:
      - db